import { DataHubContinent } from "./DataHubContinent";

export const dataHubContinentCountries: Map<DataHubContinent, string[]> = new Map([
    [
        DataHubContinent.Europe,
        [
            "Germany",
            "Italy",
            "United Kingdom",
            "France",
            "Switzerland",
            "Netherlands",
            "Greece",
            "Poland",
            "Ukraine",
            "Austria",
            "Sweden",
            "Belgium",
            "Norway",
            "Croatia",
            "Denmark",
            "Irland",
            "Finland",
            "Iceland",
            "Romania",
            "Albania",
            "Malta",
            "Czech Republic",
            "Hungary",
            "Luxembourg",
            "Bulgaria",
            "Cyprus",
            "Serbia",
            "Montenegro",
            "Lithuania",
            "Slovakia",
            "Estonia",
            "Latvia",
            "Liechtenstein",
            "North Macedonia",
            "Vatican",
            "Belarus",
            "Monaco",
            "Bosnia and Herzegovina",
            "Andorra",
            "Kosovo",
            "Moldavia",
            "Isle of Man",
            "Faroe Islands",
            "San Marino",
            "Gibraltar",
            "Aland",
            "Jersey"
        ]
    ]
]);
